name: in-context-learning
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - defaults
dependencies:
  - cuda-nvcc=12.1.66=0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - pytorch
  - pip:
      - packaging
      - causal-conv1d>=1.1.0
      - funcy==1.15
      - mamba_ssm==1.1.1
      - matplotlib==3.7.4
      - munch==2.5.0
      - numpy==1.24.4
      - pandas==2.0.3
      - PyYAML==5.4
      - PyYAML==6.0.1
      - quinine==0.3.0
      - scikit_learn==1.3.2
      - seaborn==0.13.1
      - torch==2.1.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - xgboost==2.0.3
